MAP_AUTOMATON_WHITELIST =
{
	[1940] = {en="Chimera Ripper", 	display=true},
	[1941] = {en="String Clipper", 	display=true},
	[1942] = {en="Arcuballista", 	display=true},
	[1943] = {en="Slapstick", 		display=true},
	[1944] = {en="Shield Bash", 	display=false},
	[1945] = {en="Provoke", 		display=false},
	[1946] = {en="Shock Absorber", 	display=false},
	[1947] = {en="Flashbulb", 		display=false},
	[1948] = {en="Mana Converter", 	display=false},
	[1949] = {en="Ranged Attack", 	display=true},
	[2021] = {en="Eraser",			display=false},
	[2031] = {en="Reactive Shield",	display=false},
	[2065] = {en="Cannibal Blade", 	display=true},
	[2066] = {en="Daze",			display=true},
	[2067] = {en="Knockout", 		display=true},
	[2068] = {en="Economizer", 		display=false},
	[2299] = {en="Bone Crusher", 	display=true},
	[2300] = {en="Armor Piercer", 	display=true},
	[2301] = {en="Magic Mortar", 	display=true},
	[2743] = {en="String Shredder", display=true},
	[2744] = {en="Armor Shatterer", display=true},
	[2745] = {en="Heat Capacitor", 	display=false},
	[2746] = {en="Barrage Turbine", display=false},
	[2747] = {en="Disruptor", 		display=false},
	[2778] = {en="Reactive Shield", display=false},
	[2779] = {en="Shock Absorber", 	display=false},
	[2780] = {en="Replicator", 		display=false},
	[3485] = {en="Regulator", 		display=false},
}